version: '3'

services:
  place_fontend: # 服务名称
    image: fya392/place_fontend:1.0
    ports:
    - 80:80
    volumes:
    - /root/nginx/nginx.conf:/etc/nginx/nginx.conf # 挂载 conf 文件
    privileged: true # 解决 nginx 的文件调用权限
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=yya063514
  redis:
    image: redis:latest
  place_backend:
    image: fya392/place_backend:1.0
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis